# Generated by Django 4.0 on 2022-05-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('anio_lanzamiento', models.IntegerField()),
                ('url_portada', models.CharField(max_length=500)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.director')),
            ],
        ),
    ]
