# Generated by Django 4.0 on 2022-05-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    def insertarSuperUser(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        superuser = User.objects.create_superuser(
            username="admin",
            first_name="admin",
            last_name="admin",
            email="admin@gmail.com",
            password="admin"
        )
        superuser.save()

    operations = [
        migrations.RunPython(insertarSuperUser)
    ]
